[versions]

paperweight = "1.7.1"
paperApi = "1.20.4-R0.1-SNAPSHOT"
protocolLib = "5.2.0-SNAPSHOT"

[libraries]

protocol-lib = { module = "com.comphenix.protocol:ProtocolLib", version.ref = "protocolLib" }

[plugins]

paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }